# Project: Animal
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Animal.o Bird.o Fish.o MyString.o Sparrow.o
LINKOBJ  = main.o Animal.o Bird.o Fish.o MyString.o Sparrow.o
LIBS     = -L"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Animal.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Animal.o: Animal.cpp
	$(CPP) -c Animal.cpp -o Animal.o $(CXXFLAGS)

Bird.o: Bird.cpp
	$(CPP) -c Bird.cpp -o Bird.o $(CXXFLAGS)

Fish.o: Fish.cpp
	$(CPP) -c Fish.cpp -o Fish.o $(CXXFLAGS)

MyString.o: MyString.cpp
	$(CPP) -c MyString.cpp -o MyString.o $(CXXFLAGS)

Sparrow.o: Sparrow.cpp
	$(CPP) -c Sparrow.cpp -o Sparrow.o $(CXXFLAGS)
