# Form implementation generated from reading ui file 'grayPictureOP.ui'
#
# Created by: PyQt6 UI code generator 6.0.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_gray_picture_op(object):
    def setupUi(self, gray_picture_op):
        gray_picture_op.setObjectName("gray_picture_op")
        gray_picture_op.resize(721, 418)
        self.verticalLayout = QtWidgets.QVBoxLayout(gray_picture_op)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(gray_picture_op)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.Alignment.AlignCenter)
        self.label_2 = QtWidgets.QLabel(gray_picture_op)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2, 0, QtCore.Qt.Alignment.AlignCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.source_picture = QtWidgets.QGraphicsView(gray_picture_op)
        self.source_picture.setObjectName("source_picture")
        self.horizontalLayout_2.addWidget(self.source_picture)
        self.histogram_equalizied_picture = QtWidgets.QGraphicsView(gray_picture_op)
        self.histogram_equalizied_picture.setObjectName("histogram_equalizied_picture")
        self.horizontalLayout_2.addWidget(self.histogram_equalizied_picture)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.open_picture = QtWidgets.QPushButton(gray_picture_op)
        self.open_picture.setObjectName("open_picture")
        self.horizontalLayout_3.addWidget(self.open_picture)
        self.color2gray = QtWidgets.QPushButton(gray_picture_op)
        self.color2gray.setObjectName("color2gray")
        self.horizontalLayout_3.addWidget(self.color2gray)
        self.equalize = QtWidgets.QPushButton(gray_picture_op)
        self.equalize.setObjectName("equalize")
        self.horizontalLayout_3.addWidget(self.equalize)
        self.average_op = QtWidgets.QPushButton(gray_picture_op)
        self.average_op.setObjectName("average_op")
        self.horizontalLayout_3.addWidget(self.average_op)
        self.midium_op = QtWidgets.QPushButton(gray_picture_op)
        self.midium_op.setObjectName("midium_op")
        self.horizontalLayout_3.addWidget(self.midium_op)
        self.close_software = QtWidgets.QPushButton(gray_picture_op)
        self.close_software.setObjectName("close_software")
        self.horizontalLayout_3.addWidget(self.close_software)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(gray_picture_op)
        QtCore.QMetaObject.connectSlotsByName(gray_picture_op)

    def retranslateUi(self, gray_picture_op):
        _translate = QtCore.QCoreApplication.translate
        gray_picture_op.setWindowTitle(_translate("gray_picture_op", "灰度图像处理-20271259-张芝玮"))
        self.label.setText(_translate("gray_picture_op", "原始图像"))
        self.label_2.setText(_translate("gray_picture_op", "变化后的图像"))
        self.open_picture.setText(_translate("gray_picture_op", "打开图片"))
        self.color2gray.setText(_translate("gray_picture_op", "彩图灰度化"))
        self.equalize.setText(_translate("gray_picture_op", "直方图均衡化"))
        self.average_op.setText(_translate("gray_picture_op", "均值滤波"))
        self.midium_op.setText(_translate("gray_picture_op", "中值滤波"))
        self.close_software.setText(_translate("gray_picture_op", "关闭"))
